version: '3'


services:
  app:
    container_name: fastapi
    build: .
    working_dir: /code
    command: "uvicorn app.main:app --host 0.0.0.0 --port 80"
    restart: always
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached


volumes:
  postgres_data: